### ISSUE TITLE
Call to undefined method DocuSign\eSign\ApiClient::swaggerTypes() 

### ISSUE THREAD

**Issue by SamiullahMahjoor** [docusign/eg-01-php-jwt#5]
Hi!
When I go for creating embed sign cermony using this code, it gives this error
Can anybody guid me on this.
Thanks!

**Comment by LarryKlugerDS** [comment]
Hi @SamiullahMahjoor , please ask this type of DocuSign programming question on StackOverflow.

Please include all relevant information and the part of your code that is generating the error.

I suggest that your first steps to understand what is happening is to:

1. Get this code example running as is.

2. Get the [eg-03-php-auth-code-grant ](https://github.com/docusign/eg-03-php-auth-code-grant) code example running since it shows how to create an embedded signing session.

Then combine the two examples together as needed by your application.
